# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 18:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseUnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SaleUnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SellableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('internal_ref', models.CharField(blank=True, default='', max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sellableitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.SellableItem')),
            ],
            bases=('product.sellableitem',),
        ),
        migrations.AddField(
            model_name='sellableitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='sellableitem',
            name='item_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.ProductType'),
        ),
        migrations.AddField(
            model_name='saleunitofmeasurement',
            name='unit_of_measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.UnitOfMeasurement'),
        ),
        migrations.AddField(
            model_name='purchaseunitofmeasurement',
            name='unit_of_measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.UnitOfMeasurement'),
        ),
        migrations.AddField(
            model_name='saleunitofmeasurement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='purchaseunitofmeasurement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_units_of_measurement',
            field=models.ManyToManyField(related_name='purchase_units_of_measurement', through='product.PurchaseUnitOfMeasurement', to='product.UnitOfMeasurement'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_units_of_measurement',
            field=models.ManyToManyField(related_name='sale_units_of_measurement', through='product.SaleUnitOfMeasurement', to='product.UnitOfMeasurement'),
        ),
    ]
