# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellableitem',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
