# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_units_of_measurement',
            field=models.ManyToManyField(blank=True, related_name='purchase_units_of_measurement', through='product.PurchaseUnitOfMeasurement', to='product.UnitOfMeasurement'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_units_of_measurement',
            field=models.ManyToManyField(blank=True, related_name='sale_units_of_measurement', through='product.SaleUnitOfMeasurement', to='product.UnitOfMeasurement'),
        ),
    ]
