# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='sellableitem',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='unitofmeasurement',
            name='uuid',
        ),
    ]
