# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20161013_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_units_of_measurement',
            field=models.ManyToManyField(related_name='purchase_uoms', to='product.UnitOfMeasurement'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_units_of_measurement',
            field=models.ManyToManyField(related_name='sale_uoms', to='product.UnitOfMeasurement'),
        ),
    ]
