# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20161119_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellableitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
