# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20161015_0318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseunitofmeasurement',
            unique_together=set([('product', 'unit_of_measurement')]),
        ),
        migrations.AlterUniqueTogether(
            name='saleunitofmeasurement',
            unique_together=set([('product', 'unit_of_measurement')]),
        ),
    ]
