# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20161014_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseUnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SaleUnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_units_of_measurement',
            field=models.ManyToManyField(related_name='purchase_units_of_measurement', through='product.PurchaseUnitOfMeasurement', to='product.UnitOfMeasurement'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_units_of_measurement',
            field=models.ManyToManyField(related_name='sale_units_of_measurement', through='product.SaleUnitOfMeasurement', to='product.UnitOfMeasurement'),
        ),
        migrations.AddField(
            model_name='saleunitofmeasurement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='saleunitofmeasurement',
            name='unit_of_measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.UnitOfMeasurement'),
        ),
        migrations.AddField(
            model_name='purchaseunitofmeasurement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='purchaseunitofmeasurement',
            name='unit_of_measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.UnitOfMeasurement'),
        ),
    ]
