# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internal_ref',
            field=models.CharField(default='', max_length=100),
        ),
    ]
