# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20161015_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'permissions': (('manage_productcategories', 'Manage product categories'),)},
        ),
    ]
