# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20161015_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'permissions': (('manage-producttypes', 'Manage product types'),)},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasurement',
            options={'permissions': (('manage-unitsofmeasurement', 'Manage units of measurement'),)},
        ),
    ]
