# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_unitofmeasurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasurement',
            name='unit',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
