# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('manage-products', 'Manage products'),)},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasurement',
            options={},
        ),
    ]
