# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20161009_1611'),
        ('product', '0012_auto_20161007_1538'),
    ]

    operations = [
    ]
