# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='phonetype',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='website',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='websitetype',
            name='uuid',
        ),
    ]
