# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_paymentterm_salesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='total_price',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=19),
        ),
    ]
